
package fr.adaming.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWebService", targetNamespace = "http://webservice.adaming.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroToDinar", targetNamespace = "http://webservice.adaming.fr/", className = "fr.adaming.webservice.ConversionEuroToDinar")
    @ResponseWrapper(localName = "conversionEuroToDinarResponse", targetNamespace = "http://webservice.adaming.fr/", className = "fr.adaming.webservice.ConversionEuroToDinarResponse")
    @Action(input = "http://webservice.adaming.fr/BanqueWebService/conversionEuroToDinarRequest", output = "http://webservice.adaming.fr/BanqueWebService/conversionEuroToDinarResponse")
    public double conversionEuroToDinar(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param id
     * @return
     *     returns fr.adaming.webservice.Compte
     */
    @WebMethod
    @WebResult(name = "Compte", targetNamespace = "")
    @RequestWrapper(localName = "getCompteById", targetNamespace = "http://webservice.adaming.fr/", className = "fr.adaming.webservice.GetCompteById")
    @ResponseWrapper(localName = "getCompteByIdResponse", targetNamespace = "http://webservice.adaming.fr/", className = "fr.adaming.webservice.GetCompteByIdResponse")
    @Action(input = "http://webservice.adaming.fr/BanqueWebService/getCompteByIdRequest", output = "http://webservice.adaming.fr/BanqueWebService/getCompteByIdResponse")
    public Compte getCompteById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<fr.adaming.webservice.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllComptes", targetNamespace = "http://webservice.adaming.fr/", className = "fr.adaming.webservice.GetAllComptes")
    @ResponseWrapper(localName = "getAllComptesResponse", targetNamespace = "http://webservice.adaming.fr/", className = "fr.adaming.webservice.GetAllComptesResponse")
    @Action(input = "http://webservice.adaming.fr/BanqueWebService/getAllComptesRequest", output = "http://webservice.adaming.fr/BanqueWebService/getAllComptesResponse")
    public List<Compte> getAllComptes();

}
